server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: ["GET","POST","PUT","DELETE","OPTIONS"]
            allowedHeaders: ["*"]
            allowCredentials: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/api/catalog/**

        - id: negotiation-service
          uri: lb://NEGOTIATION-SERVICE
          predicates:
            - Path=/api/negotiation/**

        - id: analytics-service
          uri: lb://ANALYTICS-SERVICE
          predicates:
            - Path=/api/analytics/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payment/**

        - id: messaging-service
          uri: lb://MESSAGING-SERVICE
          predicates:
            - Path=/api/messages/**,/ws/messages/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true